package com.supervital.powerweather.models

data class HourInfo(
    val timeEpoch    : Long?       = null,
    val time         : String?    = null,
    val tempC        : Double?    = null,
    val tempF        : Double?    = null,
    val isDay        : Int?       = null,
    val condition    : ConditionInfo? = null,
    val windMph      : Double?    = null,
    val windKph      : Double?    = null,
    val windDegree   : Int?       = null,
    val windDir      : String?    = null,
    val pressureMb   : Int?       = null,
    val pressureIn   : Double?    = null,
    val precipMm     : Double?    = null,
    val precipIn     : Double?    = null,
    val snowCm       : Double?    = null,
    val humidity     : Double?    = null,
    val cloud        : Double?    = null,
    val feelslikeC   : Double?    = null,
    val feelslikeF   : Double?    = null,
    val windchillC   : Double?    = null,
    val windchillF   : Double?    = null,
    val heatindexC   : Double?    = null,
    val heatindexF   : Double?    = null,
    val dewpointC    : Double?    = null,
    val dewpointF    : Double?    = null,
    val willItRain   : Int?       = null,
    val chanceOfRain : Int?       = null,
    val willItSnow   : Int?       = null,
    val chanceOfSnow : Int?       = null,
    val visKm        : Int?       = null,
    val visMiles     : Int?       = null,
    val gustMph      : Double?    = null,
    val gustKph      : Double?    = null,
)